cabal-version: 3.0
name: string-interpolation-bench
version: 0.0.0
build-type: Simple

benchmark string-interpolation-bench
  type: exitcode-stdio-1.0
  main-is: bench.hs
  default-language: GHC2024
  build-depends:
    , base
    , deepseq
    , ghc-experimental
    , string-interpolation-shared
    , text
    , tasty
    , tasty-bench
  ghc-options: -O2 -ddump-simpl -ddump-rule-firings -ddump-rule-rewrites -ddump-to-file
