cabal-version: 3.0
name: string-interpolation-shared
version: 0.0.0
build-type: Simple

library
  exposed-modules:
    Data.Ascii
    Data.Debug
    Data.OverloadedStringsAlt
    Data.SQL
    Data.Text.Interpolate
  default-language: GHC2024
  build-depends:
    , base
    , ghc-experimental
    , template-haskell
    , text
